FROM python:3.9

WORKDIR /CTS_GEOGRAPHY

COPY ./req.txt /CTS_GEOGRAPHY/req.txt

RUN pip install --no-cache-dir --upgrade -r /CTS_GEOGRAPHY/req.txt

COPY ./source /CTS_GEOGRAPHY/app

CMD ["uvicorn", "source.app:app", "--proxy-headers", "--host",  "0.0.0.0", "--port", "80"]
