use [master]
GO
-- �.�. ������� ������
CREATE LOGIN [FAST_API_CTS_GEOGRAPHY] WITH PASSWORD=N'HhHh~12345678', DEFAULT_DATABASE=[CTS_GEOGRAPHY], DEFAULT_LANGUAGE=[russian], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

GRANT CONNECT SQL TO [FAST_API_CTS_GEOGRAPHY]
GO

ALTER LOGIN [FAST_API_CTS_GEOGRAPHY] ENABLE
GO

USE [CTS_GEOGRAPHY]
GO

/****** Object:  User [FAST_API_CTS_GEOGRAPHY]    Script Date: 12.08.2023 17:45:57 ******/
CREATE USER [FAST_API_CTS_GEOGRAPHY] FOR LOGIN [FAST_API_CTS_GEOGRAPHY] WITH DEFAULT_SCHEMA=[dbo]
GO
