use [CTS_GEOGRAPHY]
GO
GRANT EXECUTE ON [dbo].[ext#airport_import] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT VIEW DEFINITION ON [dbo].[ext#airport_import] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT DELETE ON [dbo].[spr_country] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT INSERT ON [dbo].[spr_country] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT SELECT ON [dbo].[spr_country] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT UPDATE ON [dbo].[spr_country] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT VIEW DEFINITION ON [dbo].[spr_country] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT CONNECT TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT EXECUTE ON [dbo].[api#airports] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT VIEW DEFINITION ON [dbo].[api#airports] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT DELETE ON [dbo].[spr_airport] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT INSERT ON [dbo].[spr_airport] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT SELECT ON [dbo].[spr_airport] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT UPDATE ON [dbo].[spr_airport] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT VIEW DEFINITION ON [dbo].[spr_airport] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT DELETE ON [dbo].[spr_city] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT INSERT ON [dbo].[spr_city] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT SELECT ON [dbo].[spr_city] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT UPDATE ON [dbo].[spr_city] TO [FAST_API_CTS_GEOGRAPHY]
GO
use [CTS_GEOGRAPHY]
GO
GRANT VIEW DEFINITION ON [dbo].[spr_city] TO [FAST_API_CTS_GEOGRAPHY]
GO
