DB_DRIVER = '{ODBC Driver 17 for SQL Server}'
DB_SERVER = 'DESKTOP-5G1RJA4\SQLEXPRESS'
DB_NAME = 'CTS_GEOGRAPHY'
TRUSTED_CONNECTION = 'yes'

CSV_FILEPATH = r'F:\Delphi\CTS_GEOGRAPHY\AirportsImport\apinfo.ru.csv'
CSV_COLUMN_AIRPORT_IATA_CODE = 0
CSV_COLUMN_AIRPORT_NAME_RUS = 2
CSV_COLUMN_AIRPORT_NAME_ENG = 4
CSV_COLUMN_AIRPORT_LATITUDE = 14
CSV_COLUMN_AIRPORT_LONGITUDE = 16
CSV_COLUMN_CITY_NAME_RUS = 6
CSV_COLUMN_CITY_NAME_ENG = 8
CSV_COLUMN_COUNTRY_NAME_RUS = 10
CSV_COLUMN_COUNTRY_ISO = 12
